(()=>{'use strict';const form=document.querySelector('#beauty-form'),panels=[...document.querySelectorAll('.panel')],steps=[...document.querySelectorAll('.step')],prev=document.querySelector('#prev'),next=document.querySelector('#next'),submit=document.querySelector('#submit'),status=document.querySelector('#status'),dialog=document.querySelector('#success');let current=1;
function show(n,scroll=true){current=Math.max(1,Math.min(4,n));panels.forEach((p,i)=>{p.hidden=i+1!==current;p.classList.toggle('active',i+1===current)});steps.forEach((s,i)=>{s.classList.toggle('active',i+1===current);s.classList.toggle('done',i+1<current);s.toggleAttribute('aria-current',i+1===current)});prev.hidden=current===1;next.hidden=current===4;submit.hidden=current!==4;status.classList.remove('show');if(scroll)document.querySelector('#captacion').scrollIntoView({behavior:'smooth',block:'start'})}
function validate(panel){let valid=true;panel.querySelectorAll('[required]').forEach(input=>{const field=input.closest('.field')||input.closest('.consent');field?.classList.remove('invalid');input.setAttribute('aria-invalid','false');const error=field?.querySelector('.error');if(error)error.textContent='';if(!input.checkValidity()){valid=false;field?.classList.add('invalid');input.setAttribute('aria-invalid','true');if(error)error.textContent=input.validity.valueMissing?'Este campo es necesario.':'Revisa este dato.'}});if(!valid){status.textContent='Revisa los campos señalados antes de continuar.';status.classList.add('show');panel.querySelector('[aria-invalid="true"]')?.focus()}return valid}
next.addEventListener('click',()=>validate(panels[current-1])&&show(current+1));prev.addEventListener('click',()=>show(current-1));steps.forEach(s=>s.addEventListener('click',()=>{const n=Number(s.dataset.go);if(n<=current||validate(panels[current-1]))show(n)}));
function thirdParty(){const visible=document.querySelector('#referrals').children.length+document.querySelector('#wishlist-contacts').children.length>0,box=document.querySelector('.third');box.classList.toggle('show',visible);box.querySelector('input').required=visible}
function add(kind,max){const container=document.querySelector(kind==='referral'?'#referrals':'#wishlist-contacts');if(container.children.length>=max)return;const frag=document.querySelector(`#${kind}-template`).content.cloneNode(true),row=frag.querySelector('.row'),index=container.children.length,group=kind==='referral'?'referrals':'share_wishlist_with';row.querySelectorAll('[data-name]').forEach(i=>i.name=`${group}[${index}][${i.dataset.name}]`);row.querySelector('.remove').addEventListener('click',()=>{row.remove();thirdParty()});container.appendChild(frag);thirdParty()}
document.querySelectorAll('.add').forEach(b=>b.addEventListener('click',()=>add(b.dataset.kind,Number(b.dataset.max))));
function fillDemoData(){
  const random=new Uint32Array(2);crypto.getRandomValues(random);const suffix=String(random[0]).padStart(10,'0').slice(-10),pick=(values,offset=0)=>values[(random[1]+offset)%values.length],setValue=(name,value)=>{const input=form.elements.namedItem(name);if(input)input.value=value},setChecked=(name,values)=>{form.querySelectorAll(`[name="${name}"]`).forEach(input=>{input.checked=values.includes(input.value)})};
  form.reset();document.querySelector('#referrals').replaceChildren();document.querySelector('#wishlist-contacts').replaceChildren();thirdParty();form.querySelectorAll('.invalid').forEach(node=>node.classList.remove('invalid'));form.querySelectorAll('[aria-invalid]').forEach(input=>input.setAttribute('aria-invalid','false'));
  setValue('full_name',`Demo ${pick(['Alba','Clara','Irene','Lucía'])} ${suffix.slice(-4)}`);setValue('phone_mobile',`+34 6${suffix.slice(-8)}`);setValue('email',`katy.demo.${suffix}@demo.example`);setValue('birthday',pick(['1988-04-12','1994-09-26','2000-02-14']));setValue('profession',pick(['Diseño','Docencia','Tecnología','Ventas']));setValue('address',pick(['Barcelona','Cornellà de Llobregat','L’Hospitalet']));setValue('best_contact_time',pick(['Mañana','Tarde','Noche']));setValue('important_facts','Perfil sintético generado para validar el flujo de demostración.');
  setChecked('preferred_contact_channels',['WhatsApp']);setChecked('age_range',[pick(['26-35','36-50','50+'])]);setChecked('skin_feel',[pick(['Seca o tirante','Ni seca ni grasa','Grasa en la zona T'])]);setChecked('basic_skincare_needs',['Limpieza','Hidratación']);setChecked('skin_concerns',[pick(['Textura','Poros visibles','Tono apagado'])]);setValue('eye_concerns','Hidratación y luminosidad');setValue('lip_concerns','Hidratación');setValue('current_skincare_routine','Limpieza e hidratación por la mañana y por la noche.');
  setChecked('interests',['Cuidado facial','Maquillaje']);setValue('foundation_coverage',pick(['Mate','Natural','Luminoso']));setValue('foundation_type','Líquida');setChecked('desired_new_looks',[pick(['Labios rojos','Oficina chic','Natural'])]);setValue('products_tried','Limpiadora facial');setValue('products_take_home','Hidratante');setValue('wishlist','Base y labial');form.elements.namedItem('privacy_acknowledged').checked=true;form.elements.namedItem('consent_whatsapp').checked=false;form.elements.namedItem('consent_email').checked=false;form.elements.namedItem('third_party_permission').checked=false;
  show(4);status.textContent='Datos sintéticos preparados. Revisa y pulsa “Enviar mi perfil”.';status.classList.add('show');
}
document.querySelector('#demo-fill').addEventListener('click',fillDemoData);
const arrays=new Set(['preferred_contact_channels','basic_skincare_needs','skin_concerns','interests','desired_new_looks']);function serialize(){const data=new FormData(form),out={submission_id:crypto.randomUUID(),submitted_at:new Date().toISOString(),fields:{},repeaters:{referrals:[],share_wishlist_with:[]},consent:{}};for(const[k,v]of data.entries()){if(k==='website'){out.website=v;continue}if(k.startsWith('referrals[')||k.startsWith('share_wishlist_with['))continue;if(k.startsWith('consent_')||k==='privacy_acknowledged'||k==='third_party_permission')out.consent[k]=v==='on';else if(arrays.has(k))(out.fields[k]??=[]).push(v);else out.fields[k]=v}for(const group of['referrals','share_wishlist_with']){document.querySelectorAll(`[name^="${group}["]`).forEach(input=>{const m=input.name.match(/\[(\d+)\]\[([^\]]+)\]/);if(!m||!input.value.trim())return;const i=Number(m[1]);out.repeaters[group][i]??={};out.repeaters[group][i][m[2]]=input.value.trim()});out.repeaters[group]=out.repeaters[group].filter(Boolean)}return out}
form.addEventListener('submit',async e=>{e.preventDefault();if(!validate(panels[current-1]))return;const payload=serialize();submit.classList.add('loading');submit.disabled=true;submit.textContent='Enviando…';try{const apiBase=location.hostname.endsWith('.github.io')?'https://katy-demo.31-97-153-148.nip.io':'';const response=await fetch(`${apiBase}/api/submissions`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.message||'No se pudo enviar el formulario.');document.querySelector('#first-name').textContent=payload.fields.full_name.split(' ')[0];document.querySelector('#result-message').textContent=result.message||'Tu perfil se ha preparado correctamente.';document.querySelector('#demo-note').hidden=!result.demo_mode;dialog.showModal();form.reset();document.querySelector('#referrals').replaceChildren();document.querySelector('#wishlist-contacts').replaceChildren();thirdParty();show(1,false)}catch(error){status.textContent=error.message||'Ha ocurrido un error.';status.classList.add('show')}finally{submit.classList.remove('loading');submit.disabled=false;submit.textContent='Enviar mi perfil ♡'}});document.querySelector('#close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});show(1,false)})();